-- MySQL Script generated by MySQL Workbench
-- Mon May  8 12:16:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema awdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema awdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awdb` DEFAULT CHARACTER SET utf8mb3 ;
USE `awdb` ;

-- -----------------------------------------------------
-- Table `awdb`.`budgetperiod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`budgetperiod` ;

CREATE TABLE IF NOT EXISTS `awdb`.`budgetperiod` (
  `CalendarYear` INT NULL DEFAULT NULL,
  `MonthName` VARCHAR(45) NULL DEFAULT NULL,
  `MonthNumber` TINYINT NULL DEFAULT NULL,
  `Period` INT NOT NULL,
  PRIMARY KEY (`Period`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`budget` ;

CREATE TABLE IF NOT EXISTS `awdb`.`budget` (
  `Category` VARCHAR(45) NULL DEFAULT NULL,
  `Budget` INT NULL DEFAULT NULL,
  `Period` INT NULL DEFAULT NULL,
  INDEX `FK_Period_idx` (`Period` ASC) VISIBLE,
  CONSTRAINT `FK_Period`
    FOREIGN KEY (`Period`)
    REFERENCES `awdb`.`budgetperiod` (`Period`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`customer` ;

CREATE TABLE IF NOT EXISTS `awdb`.`customer` (
  `CustomerKey` INT NOT NULL,
  `GeographyKey` INT NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `BirthDate` DATE NULL DEFAULT NULL,
  `MaritalStatus` ENUM('M', 'S') NULL DEFAULT NULL,
  `Gender` ENUM('M', 'F') NULL DEFAULT NULL,
  `YearlyIncome` INT NULL DEFAULT NULL,
  `NumberChildrenAtHome` TINYINT NULL DEFAULT NULL,
  `Occupation` VARCHAR(45) NULL DEFAULT NULL,
  `HouseOwnerFlag` TINYINT NULL DEFAULT NULL,
  `NumberCarsOwned` TINYINT NULL DEFAULT NULL,
  `AddressLine1` VARCHAR(100) NULL DEFAULT NULL,
  `AddressLine2` VARCHAR(100) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `DateFirstPurchase` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`dimdate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dimdate` ;

CREATE TABLE IF NOT EXISTS `awdb`.`dimdate` (
  `DateKey` INT NOT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `YearMonthNum` INT NULL DEFAULT NULL,
  `Year` INT NULL DEFAULT NULL,
  `Calendar_Quarter` VARCHAR(10) NULL DEFAULT NULL,
  `MonthNum` INT NULL DEFAULT NULL,
  `MonthName` VARCHAR(45) NULL DEFAULT NULL,
  `MonthShortName` VARCHAR(45) NULL DEFAULT NULL,
  `WeekNum` INT NULL DEFAULT NULL,
  `DayNumOfYear` INT NULL DEFAULT NULL,
  `DayNumOfMonth` INT NULL DEFAULT NULL,
  `DayNumOfWeek` INT NULL DEFAULT NULL,
  `DayName` VARCHAR(45) NULL DEFAULT NULL,
  `DayShortName` VARCHAR(45) NULL DEFAULT NULL,
  `Quarter` INT NULL DEFAULT NULL,
  `YearQuarterNum` INT NULL DEFAULT NULL,
  `DayNumOfQuarter` INT NULL DEFAULT NULL,
  PRIMARY KEY (`DateKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`dimproductcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dimproductcategory` ;

CREATE TABLE IF NOT EXISTS `awdb`.`dimproductcategory` (
  `ProductCategoryKey` INT NOT NULL,
  `ProductCategoryAlternateKey` INT NULL DEFAULT NULL,
  `EnglishProductCategoryName` VARCHAR(45) NULL DEFAULT NULL,
  `SpanishProductCategoryName` VARCHAR(45) NULL DEFAULT NULL,
  `FrenchProductCategoryName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductCategoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`dimproductsubcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dimproductsubcategory` ;

CREATE TABLE IF NOT EXISTS `awdb`.`dimproductsubcategory` (
  `ProductSubcategoryKey` INT NOT NULL,
  `ProductSubcategoryAlternateKey` TINYINT NULL DEFAULT NULL,
  `EnglishProductSubcategoryName` VARCHAR(100) NULL DEFAULT NULL,
  `SpanishProductSubcategoryName` VARCHAR(100) NULL DEFAULT NULL,
  `FrenchProductSubcategoryName` VARCHAR(100) NULL DEFAULT NULL,
  `ProductCategoryKey` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ProductSubcategoryKey`),
  INDEX `FK_ProductCategoryKey_idx` (`ProductCategoryKey` ASC) VISIBLE,
  CONSTRAINT `FK_ProductCategoryKey`
    FOREIGN KEY (`ProductCategoryKey`)
    REFERENCES `awdb`.`dimproductcategory` (`ProductCategoryKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`product` ;

CREATE TABLE IF NOT EXISTS `awdb`.`product` (
  `ProductKey` INT NOT NULL,
  `ProductSubcategoryKey` INT NULL DEFAULT NULL,
  `ProductName` VARCHAR(100) NULL DEFAULT NULL,
  `StandardCost` DECIMAL(10,0) NULL DEFAULT NULL,
  `Color` VARCHAR(45) NULL DEFAULT NULL,
  `SafetyStockLevel` INT NULL DEFAULT NULL,
  `ListPrice` DECIMAL(10,0) NULL DEFAULT NULL,
  `Size` TINYINT NULL DEFAULT NULL,
  `SizeRange` VARCHAR(45) NULL DEFAULT NULL,
  `Weight` DECIMAL(10,0) NULL DEFAULT NULL,
  `DaysToManufacture` TINYINT NULL DEFAULT NULL,
  `ProductLine` VARCHAR(3) NULL DEFAULT NULL,
  `DealerPrice` DECIMAL(10,0) NULL DEFAULT NULL,
  `Class` VARCHAR(3) NULL DEFAULT NULL,
  `ModelName` VARCHAR(45) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `SubCategory` VARCHAR(45) NULL DEFAULT NULL,
  `Category` VARCHAR(45) NULL DEFAULT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ProductKey`),
  INDEX `FK_ProductSubCategoryKey_idx` (`ProductSubcategoryKey` ASC) VISIBLE,
  CONSTRAINT `FK_ProductSubCategoryKey`
    FOREIGN KEY (`ProductSubcategoryKey`)
    REFERENCES `awdb`.`dimproductsubcategory` (`ProductSubcategoryKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`territory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`territory` ;

CREATE TABLE IF NOT EXISTS `awdb`.`territory` (
  `TerritoryKey` INT NOT NULL,
  `Region` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `GroupRegion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`TerritoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `awdb`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`sales` ;

CREATE TABLE IF NOT EXISTS `awdb`.`sales` (
  `OrderDate` DATE NOT NULL,
  `OrderDateKey` INT NULL DEFAULT NULL,
  `ProductKey` INT NULL DEFAULT NULL,
  `CustomerKey` INT NULL DEFAULT NULL,
  `SalesTerritoryKey` INT NULL DEFAULT NULL,
  `SalesOrderNumber` VARCHAR(45) NULL DEFAULT NULL,
  `ShipDate` DATE NULL DEFAULT NULL,
  `SalesOrderLineNumber` TINYINT NULL DEFAULT NULL,
  `OrderQuantity` TINYINT NULL DEFAULT NULL,
  `UnitPrice` DECIMAL(10,0) NULL DEFAULT NULL,
  `ExtendedAmount` DECIMAL(10,0) NULL DEFAULT NULL,
  `UnitPriceDiscountPct` TINYINT NULL DEFAULT NULL,
  `DiscountAmount` TINYINT NULL DEFAULT NULL,
  `ProductStandardCost` DECIMAL(10,0) NULL DEFAULT NULL,
  `TotalProductCost` DECIMAL(10,0) NULL DEFAULT NULL,
  `SalesAmount` DECIMAL(10,0) NULL DEFAULT NULL,
  `TaxAmt` DECIMAL(10,0) NULL DEFAULT NULL,
  `Freight` DECIMAL(10,0) NULL DEFAULT NULL,
  `RegionMonthID` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `FK_CustomerKey_idx` (`CustomerKey` ASC) VISIBLE,
  INDEX `FK_SalesTerritoryKey_idx` (`SalesTerritoryKey` ASC) VISIBLE,
  INDEX `FK_ProductKey_idx` (`ProductKey` ASC) VISIBLE,
  INDEX `FK_SalesOrderDateKey_idx` (`OrderDateKey` ASC) VISIBLE,
  CONSTRAINT `FK_CustomerKey`
    FOREIGN KEY (`CustomerKey`)
    REFERENCES `awdb`.`customer` (`CustomerKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_OrderDateKey`
    FOREIGN KEY (`OrderDateKey`)
    REFERENCES `awdb`.`dimdate` (`DateKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ProductKey`
    FOREIGN KEY (`ProductKey`)
    REFERENCES `awdb`.`product` (`ProductKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SalesTerritoryKey`
    FOREIGN KEY (`SalesTerritoryKey`)
    REFERENCES `awdb`.`territory` (`TerritoryKey`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `awdb` ;

-- -----------------------------------------------------
-- Placeholder table for view `awdb`.`dim_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awdb`.`dim_calendar` (`DateKey` INT, `Date` INT, `Day` INT, `MonthShortName` INT, `MonthNum` INT, `Quarter` INT, `Year` INT);

-- -----------------------------------------------------
-- Placeholder table for view `awdb`.`dim_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awdb`.`dim_customer` (`CustomerKey` INT, `first_name` INT, `last_name` INT, `fullname` INT, `gender` INT, `DATE(DateFirstPurchase)` INT, `occupation` INT);

-- -----------------------------------------------------
-- Placeholder table for view `awdb`.`dim_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awdb`.`dim_product` (`product_key` INT, `product_name` INT, `subcategory` INT, `category` INT, `color` INT, `size` INT, `product_line` INT, `model_name` INT, `product_status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `awdb`.`fact_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awdb`.`fact_sales` (`OrderDateKey` INT, `ProductKey` INT, `CustomerKey` INT, `SalesOrderLineNumber` INT, `SalesAmount` INT);

-- -----------------------------------------------------
-- View `awdb`.`dim_calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dim_calendar`;
DROP VIEW IF EXISTS `awdb`.`dim_calendar` ;
USE `awdb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `awdb`.`dim_calendar` AS select `awdb`.`dimdate`.`DateKey` AS `DateKey`,`awdb`.`dimdate`.`Date` AS `Date`,`awdb`.`dimdate`.`DayName` AS `Day`,`awdb`.`dimdate`.`MonthShortName` AS `MonthShortName`,`awdb`.`dimdate`.`MonthNum` AS `MonthNum`,`awdb`.`dimdate`.`Quarter` AS `Quarter`,`awdb`.`dimdate`.`Year` AS `Year` from `awdb`.`dimdate` where ((`awdb`.`dimdate`.`Year` = 2016) and (`awdb`.`dimdate`.`MonthNum` = 7));

-- -----------------------------------------------------
-- View `awdb`.`dim_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dim_customer`;
DROP VIEW IF EXISTS `awdb`.`dim_customer` ;
USE `awdb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `awdb`.`dim_customer` AS select `awdb`.`customer`.`CustomerKey` AS `CustomerKey`,`awdb`.`customer`.`FirstName` AS `first_name`,`awdb`.`customer`.`LastName` AS `last_name`,concat(`awdb`.`customer`.`FirstName`,' ',`awdb`.`customer`.`LastName`) AS `fullname`,(case `awdb`.`customer`.`Gender` when 'M' then 'Male' when 'F' then 'Female' end) AS `gender`,cast(`awdb`.`customer`.`DateFirstPurchase` as date) AS `DATE(DateFirstPurchase)`,`awdb`.`customer`.`Occupation` AS `occupation` from `awdb`.`customer`;

-- -----------------------------------------------------
-- View `awdb`.`dim_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`dim_product`;
DROP VIEW IF EXISTS `awdb`.`dim_product` ;
USE `awdb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `awdb`.`dim_product` AS select `p`.`ProductKey` AS `product_key`,`p`.`ProductName` AS `product_name`,`ps`.`EnglishProductSubcategoryName` AS `subcategory`,`pc`.`EnglishProductCategoryName` AS `category`,`p`.`Color` AS `color`,`p`.`Size` AS `size`,`p`.`ProductLine` AS `product_line`,`p`.`ModelName` AS `model_name`,ifnull(`p`.`Status`,'Outdated') AS `product_status` from ((`awdb`.`product` `p` left join `awdb`.`dimproductsubcategory` `ps` on((`p`.`ProductSubcategoryKey` = `ps`.`ProductSubcategoryKey`))) left join `awdb`.`dimproductcategory` `pc` on((`pc`.`ProductCategoryKey` = `ps`.`ProductCategoryKey`))) order by `p`.`ProductKey`;

-- -----------------------------------------------------
-- View `awdb`.`fact_sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awdb`.`fact_sales`;
DROP VIEW IF EXISTS `awdb`.`fact_sales` ;
USE `awdb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `awdb`.`fact_sales` AS select `awdb`.`sales`.`OrderDateKey` AS `OrderDateKey`,`awdb`.`sales`.`ProductKey` AS `ProductKey`,`awdb`.`sales`.`CustomerKey` AS `CustomerKey`,`awdb`.`sales`.`SalesOrderLineNumber` AS `SalesOrderLineNumber`,`awdb`.`sales`.`SalesAmount` AS `SalesAmount` from `awdb`.`sales` order by `awdb`.`sales`.`OrderDateKey`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
